//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

//using System.Reflection;

//[assembly: AssemblyFileVersion("0.1.0.0")]
//[assembly: AssemblyVersion("0.1.0.0")]
//[assembly: AssemblyInformationalVersion("0.1.0+132.Branch.main.Sha.663c6611f630ddca71672d66696d7ba904113c06")]
