//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureElementReader.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureElementReader.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at depth.
        /// </summary>
        public static string ErrorAtDepth {
            get {
                return ResourceManager.GetString("ErrorAtDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get PKI cert error.
        /// </summary>
        public static string GetPkiCertError {
            get {
                return ResourceManager.GetString("GetPkiCertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SE cert error.
        /// </summary>
        public static string GetSeCertError {
            get {
                return ResourceManager.GetString("GetSeCertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download certificates.
        /// </summary>
        public static string InstallRCAandICA {
            get {
                return ResourceManager.GetString("InstallRCAandICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RCA and ICA certificate from this url.
        /// </summary>
        public static string InstallRCAandICAurl {
            get {
                return ResourceManager.GetString("InstallRCAandICAurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKI cert details error.
        /// </summary>
        public static string PkiCertDetailsError {
            get {
                return ResourceManager.GetString("PkiCertDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a card.
        /// </summary>
        public static string PleaseInseretCard {
            get {
                return ResourceManager.GetString("PleaseInseretCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible solution.
        /// </summary>
        public static string PossibleSolution {
            get {
                return ResourceManager.GetString("PossibleSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE cert details error.
        /// </summary>
        public static string SeCertDetailsError {
            get {
                return ResourceManager.GetString("SeCertDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PKI app error.
        /// </summary>
        public static string SelectPkiError {
            get {
                return ResourceManager.GetString("SelectPkiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SE app error.
        /// </summary>
        public static string SelectSeError {
            get {
                return ResourceManager.GetString("SelectSeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inforamtion.
        /// </summary>
        public static string StatusInforamtion {
            get {
                return ResourceManager.GetString("StatusInforamtion", resourceCulture);
            }
        }
    }
}
